import "./globals.css";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import NextTopLoader from "nextjs-toploader";
import NextAuthSessionProvider from "@/providers/sessionProvider";
import { ChildrenProps } from "@/interfaces/childrenProps";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: ChildrenProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <span className="_it4vx _72fik"></span> */}
        <NextTopLoader color="#DE3163" height={2.5} />
        <NextAuthSessionProvider>
          <ToastContainer
            position="top-left"
            autoClose={5000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="colored"
          />
          {children}
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
