import "./globals.css";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import NextTopLoader from "nextjs-toploader";
import NextAuthSessionProvider from "@/providers/sessionProvider";
import { ChildrenProps } from "@/interfaces/childrenProps";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: ChildrenProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextTopLoader color="#DE3163" />
        <NextAuthSessionProvider>{children}</NextAuthSessionProvider>
      </body>
    </html>
  );
}
